### ISSUE TITLE
Server: Permissions denied

### ISSUE THREAD

**Issue by maskaz** [chrivers/bifrost#1] opened 2024-08-22 08:55 UTC
Hi, I can't start Bifrost properly because of error

Worked task failed: IOError(Os { code: 13, kind: PermissionDenied, message: "Permission denied" })

Logs below

2024-08-22T08:53:50.863Z DEBUG bifrost > Configuration loaded successfully
 2024-08-22T08:53:50.863Z DEBUG bifrost::server::certificate > Found existing certficate for bridge id [340286fffe6ee5bf]
 2024-08-22T08:53:50.863Z DEBUG bifrost::state               > Existing state file found, loading..
 2024-08-22T08:53:50.864Z INFO  bifrost::mdns                > Registered service bifrost-3402866ee5bf._hue._tcp.local.
 2024-08-22T08:53:50.864Z INFO  bifrost                      > Serving mac [34:02:86:6E:E5:BF]
 2024-08-22T08:53:50.864Z DEBUG bifrost::state               > Loading certificate from [cert.pem]
 2024-08-22T08:53:50.865Z INFO  bifrost::server              > http listening on 192.168.1.128:80
 2024-08-22T08:53:50.865Z ERROR bifrost                      > Worked task failed: IOError(Os { code: 13, kind: PermissionDenied, message: "Permission denied" })
 2024-08-22T08:53:50.865Z INFO  bifrost::server              > https listening on 192.168.1.128:443
 2024-08-22T08:53:50.865Z INFO  bifrost::z2m                 > [server1] Connecting to ws://192.168.1.110:8099
 2024-08-22T08:53:50.865Z ERROR bifrost                      > Worked task failed: IOError(Os { code: 13, kind: PermissionDenied, message: "Permission denied" })
 2024-08-22T08:53:50.873Z DEBUG tungstenite::handshake::client > Client handshake done.

**Comment by chrivers** [comment] 2024-08-22 16:04
Hello @maskaz 

Thanks for trying bifrost! It's very exciting to see it used anywhere other than my computer :smile: 

Too bad you're having trouble with it. I'm still working on the "new user experience", since there are a few things that can fail.

I realize now that I forgot to mention a thing in the README.

Bifrost needs to bind to port 80 and 443, which is not normally allowed for regular users.

You can try to run this command, to see if it helps:

```
echo 1 | sudo tee /proc/sys/net/ipv4/ip_unprivileged_port_start
```

This will echo 1 (as root, hence the `sudo tee` part) into `/proc/sys/net/ipv4/ip_unprivileged_port_start`, which controls what ports numbers non-root users can listen on.

By setting this to 1, all ports are available.

This will only work until you reboot! But it could determine what the problem is.



The other possibility, is that a file cannot be written to. Bifrost will try to read `config.yaml` + `cert.pem` from the current directory, and wants to write to `state.yaml` (as well as create `cert.pem`, if it doesn't exist).

Any chance you're running bifrost from a directory you're not allowed to write to?

**Comment by maskaz** [comment] 2024-08-22 17:12
Thank you, Bifrost started up.
It is nice to help in development.
Now i have another issue, i will create another issue.

**Comment by chrivers** [comment] 2024-08-22 20:09
That's good to hear! Thanks for the feedback :+1: 

I'll close this issue, and try to improve the documentation :)

**Closed** 2024-08-22 20:10 UTC
